// Generated by scripts/build-pons-manifest.mjs from MIT-licensed verified Pons sources.
export const PONS_MANIFEST = {
  "sourceUrl": "https://robinhoodchain.blockscout.com/api/v2/smart-contracts/0x7eD598BcEf8bd9Edd8C97A195C6d13f40801EC7e",
  "topics": {
    "CurveBuy": "0xec36bf571f136799e8dc0b0b8bea4b04d8bd3d43de838aab0d5fc21d4cbfc455",
    "CurveSell": "0x8113d738abdcb6b38357e9d53a54a7157861a09031b453651f0fe7fe151f59df"
  },
  "compiler": "0.8.35+commit.47b9dedd.Emscripten.clang",
  "factorySha256": "226a042e6d68a69a6038d4fda211925b03eb5299399434b87a7877f79f6e3848",
  "artifacts": {
    "PonsV2BondingCurve": {
      "length": 10229,
      "sha256": "412fe5d4035880f749366dab1194d18e23d3dfdeb8c6553f1522ec539af17190",
      "immutables": [
        {
          "length": 32,
          "start": 1071
        },
        {
          "length": 32,
          "start": 5741
        },
        {
          "length": 32,
          "start": 8136
        },
        {
          "length": 32,
          "start": 8301
        },
        {
          "length": 32,
          "start": 9748
        },
        {
          "length": 32,
          "start": 560
        },
        {
          "length": 32,
          "start": 1968
        },
        {
          "length": 32,
          "start": 2804
        },
        {
          "length": 32,
          "start": 3009
        },
        {
          "length": 32,
          "start": 3455
        },
        {
          "length": 32,
          "start": 4340
        },
        {
          "length": 32,
          "start": 5142
        },
        {
          "length": 32,
          "start": 6213
        },
        {
          "length": 32,
          "start": 3353
        },
        {
          "length": 32,
          "start": 5912
        },
        {
          "length": 32,
          "start": 2735
        },
        {
          "length": 32,
          "start": 9797
        },
        {
          "length": 32,
          "start": 9958
        },
        {
          "length": 32,
          "start": 937
        },
        {
          "length": 32,
          "start": 7277
        },
        {
          "length": 32,
          "start": 3665
        },
        {
          "length": 32,
          "start": 5355
        },
        {
          "length": 32,
          "start": 5471
        },
        {
          "length": 32,
          "start": 7205
        },
        {
          "length": 32,
          "start": 7423
        },
        {
          "length": 32,
          "start": 8081
        },
        {
          "length": 32,
          "start": 5809
        },
        {
          "length": 32,
          "start": 7383
        },
        {
          "length": 32,
          "start": 3236
        },
        {
          "length": 32,
          "start": 5227
        },
        {
          "length": 32,
          "start": 6966
        },
        {
          "length": 32,
          "start": 7895
        },
        {
          "length": 32,
          "start": 8771
        },
        {
          "length": 32,
          "start": 5655
        },
        {
          "length": 32,
          "start": 8821
        },
        {
          "length": 32,
          "start": 3173
        },
        {
          "length": 32,
          "start": 7669
        },
        {
          "length": 32,
          "start": 1905
        },
        {
          "length": 32,
          "start": 2105
        },
        {
          "length": 32,
          "start": 3815
        },
        {
          "length": 32,
          "start": 6596
        },
        {
          "length": 32,
          "start": 1426
        },
        {
          "length": 32,
          "start": 3894
        },
        {
          "length": 32,
          "start": 4958
        },
        {
          "length": 32,
          "start": 6353
        },
        {
          "length": 32,
          "start": 1478
        },
        {
          "length": 32,
          "start": 2875
        },
        {
          "length": 32,
          "start": 3944
        },
        {
          "length": 32,
          "start": 5008
        },
        {
          "length": 32,
          "start": 2141
        },
        {
          "length": 32,
          "start": 3296
        }
      ]
    },
    "PonsV2LauncherToken": {
      "length": 3248,
      "sha256": "4863376dd612d9d23f5e8c25eb84aecfe5a317764ba543497f6d14c9a70e64ea",
      "immutables": [
        {
          "length": 32,
          "start": 379
        },
        {
          "length": 32,
          "start": 529
        },
        {
          "length": 32,
          "start": 1357
        },
        {
          "length": 32,
          "start": 1094
        }
      ]
    }
  },
  "selectors": {
    "getLaunchedToken(address)": "0x3cf28b5a",
    "token()": "0xfc0c546a",
    "factory()": "0xc45a0155",
    "pairToken()": "0x3de35b79",
    "graduated()": "0xe7c2b772",
    "readyToGraduate()": "0xc68360a5",
    "getReserves()": "0x0902f1ac",
    "realQuoteReserve()": "0x4f1f58fd",
    "feeBps()": "0x24a9d853",
    "creatorTaxBps()": "0xc1bb8901",
    "decimals()": "0x313ce567",
    "balanceOf(address)": "0x70a08231",
    "buy(uint256,uint256,address)": "0x59a87bc1",
    "sell(uint256,uint256,address)": "0xd04c6983",
    "approve(address,uint256)": "0x095ea7b3",
    "currentSnipeTaxBps(address)": "0xd7e1ef39",
    "snipeTaxExempt(address)": "0xd44bdfe7"
  }
} as const;
